### ISSUE TITLE
On refresh in products view, getting redirected to login page

### ISSUE THREAD

**Issue by rujool** [rujool/GroceryStore#1]
On refreshing the products view, currently getting redirected to login page. It seems we need to use promise for $resource while fetching products.

**Comment by rujool** [comment]
Fixed this bug by setting the variables within the resource call, and not using the service. @UTKGANDHI @harshbhalani12 can someone verify if it is fixed so we can close the issue?

**Comment by UTKGANDHI** [comment]
Verified. Working!
